Feat jwt token
Axel-Pion-MDS/M1_Project_Timer_Back pull request #8
Opened 2022-12-13 23:18 UTC by Lucas-Malatchoumy

# Merge feat-jwt-tokeninto S1
## Features

### user
- Create jwt for users after login
- Create jwt for users after registering

## Changes
- **user/url.py**: pass id in body in update request (not in parameters)
- **user/views.py**: import *jwt* package

2022-12-14 12:48 UTC, Maengdok requested changes

2022-12-14 12:48 UTC, Maengdok commented on user/views.py
>                  message = 'You are logged in'
Ta variable n'est jamais utilisée ?

2022-12-14 12:48 UTC, Maengdok commented on user/views.py
> +                user = User.objects.get(email=email)
Pourquoi fais tu une seconde récupération de l'utilisateur alors que t'en fais déjà une à la ligne 30 ?

2022-12-14 12:48 UTC, Maengdok commented on user/views.py
>              if check_password:
Essaye de favoriser les vérifications négatives afin de réduire les niveaux d'imbrication


Ex.: 

```python
def login(request):
    # ...
    
    if not check_password: # Si la condition est vraie, return l'erreur sous format JSON
        return JsonResponse({
            'code': settings.HTTP_CONSTANTS['NOT_ALLOWED'],
            'result': 'Not Allowed',
            'message': 'password incorrect',
        })
    
    data = user_normalizer(user) # Si la condition est fausse, continue l'exécution du code
    # ...

```

Je l'ai perso pas fait tout le temps, mais j'en suis conscient, donc je repasserais dessus pour clear tout ce que j'ai oublié.

2022-12-14 12:49 UTC, Maengdok approved these changes

2022-12-14 12:50 UTC, Maengdok commented on user/views.py
>              if check_password:
Celle-ci n'est pas forcément obligatoire, juste du clean code.

2022-12-15 12:46 UTC, sylvaindnd approved these changes

2022-12-15 18:25 UTC, Lucas-Malatchoumy commented on user/views.py
>              if check_password:
[7370294](https://github.com/Axel-Pion-MDS/M1_Project_Timer_Back/pull/8/commits/737029446f01e222d99d5071665d8d2791aad2ad)

2022-12-15 18:25 UTC, Lucas-Malatchoumy commented on user/views.py
> +                user = User.objects.get(email=email)
[7370294](https://github.com/Axel-Pion-MDS/M1_Project_Timer_Back/pull/8/commits/737029446f01e222d99d5071665d8d2791aad2ad)

2022-12-15 18:25 UTC, Lucas-Malatchoumy commented on user/views.py
>                  message = 'You are logged in'
[7370294](https://github.com/Axel-Pion-MDS/M1_Project_Timer_Back/pull/8/commits/737029446f01e222d99d5071665d8d2791aad2ad)

2022-12-18 13:31 UTC, Maengdok approved these changes

2022-12-18 13:31 UTC, merged